name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Verify OS
        run: |
          cat /etc/os-release
          uname -a
          
      - name: Simple Success Step
        run: echo "This is a successful test!"